### ISSUE TITLE
Snapping

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-web#192]
My issues:
I was unable to make points snap to anything. 

My concerns:
My snapping settings stayed after canceling/finishing. The next time I went to draw the snapping was still active. I do not notice a place in the code where snapping is disabled unless you undo what you did in the drawing toolbar. This may be ok for others, but I think I would prefer it to possibly disable after I hit cancel on the current drawing/modification. I would expect it to reset when I cancel the entire add/modify step.

**Comment by stdavis** [comment]
I'll checkout the point snapping.

I thought the exact opposite about resetting the snapping between drawing/editing different features. I thought that the user would want it to remember what snapping they had turned on. I wouldn't think that it has any effect on performance since the edit & draw toolbars are deactivated when the draw toolbar is hidden. I think that we should get the client to make the call on this.

**Comment by stdavis** [comment]
Hmm. Maybe no snapping for multi-point features: http://jsbin.com/cimoha/edit?js,output

**Comment by stdavis** [comment]
@jpechmann Can you ask the client what they want to do on this? Should snapping checkboxes be persisted between drawing or editing different features? Or should they be reset each time the drawing toolbar is hidden?

**Comment by steveoh** [comment]
closed by https://github.com/agrc/wri-web/pull/189#issuecomment-162591727
